version: "3.8"
services:
        database:
                build:
                        context: .
                        dockerfile: Dockerfile_Database
                restart: always
                env_file:
                        - .env
                ports:
                        - "5432:5432"
        server:
                build:
                        context: .
                        dockerfile: Dockerfile_Server
                env_file: .env
                depends_on:
                        - database
                networks:
                        - default
                ports:
                        - "8010:8010"
