# Dockerfile for building test container
# Start from a Debian image with the latest version of Go installed
# and a workspace (GOPATH) configured at /go.
FROM golang

# Copy the local package files to the container's workspace.
ADD . /go/src/github.com/GabeIB/message-board-backend/server

# Build the outyet command inside the container.
# (You may fetch or manage dependencies here,
# either manually or with a tool like "godep".)
RUN go get github.com/gorilla/mux
RUN go get github.com/lib/pq

WORKDIR "/go/src/github.com/GabeIB/message-board-backend/server/app"

CMD ["go", "test", "-v", "-race"]
